gotify:
  url: [[ URL ]]
  apiToken: [[ API_TOKEN ]]
  pollTime: [[ POLTIME_CRON_JOB e.g. "*/10 * * * * *" for all 10s ]]
matrix:
  homeserverURL: [[ MATRIX_HOMESERVER_URL]]
  username: [[ MATRIX_BOT_USERNAME ]]
  password: [[ MATRIX_BOT_PASSWORD ]]
  token: [[ MATRIX_BOT_API_TOKEN ]]
  roomID: [[ ID_OF_MATRIX_ROOM ]]
  encrypted: [[ true of encryption should be enabled ]]
debug: [[ DEBUG_MODE ]]
